### ISSUE TITLE
how to change logo when we have two arabic and english

### ISSUE THREAD

**Issue by addikhann** [ahmadajmi/multilingualwithangular#2]
Can you please explain how to change image , ? When one logo english  and scond is arabic arabic 
```

   <img alt="Venue" src="img/logo-ar.png" data-logo-height="35">
   <img alt="Venue" src="img/logo.png" data-logo-height="35">
```

**Comment by ahmadajmi** [comment]
Hey, I think this repo I did before would be helpful and the readme about the translation 

https://github.com/ahmadajmi/showcase

How translation works

https://github.com/ahmadajmi/showcase#translation

It's been about 2 years since I worked with angular and also things have changed a lot since then and I hope you found the concepts in the above app useful.
